sonar.projectKey=Pankeet_Excal.com
sonar.organization=pankeet04 
sonar.sources=apps,packages
sonar.exclusions=node_modules/**,.next/**,dist/**
sonar.sourceEncoding=UTF-8
sonar.exclusions=packages/db-local/prisma/migrations/**,**/*.sql
sonar.javascript.lcov.reportPaths=apps/http-server/coverage/lcov.info